services:
  database:
    image: postgres:13
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
  server:
    build:
      dockerfile: ../backend/Dockerfile
      context: ../backend
    env_file: .env
    depends_on:
      - database
    ports:
      - "8080:8080"
volumes:
  pg_data: {}