services:
  database:
    image: postgres:13
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    env_file: .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "127.0.0.1:5432:5432"
  server:
    build:
      dockerfile: ../backend/Dockerfile
      context: ../backend
    env_file: .env
    depends_on:
      - database
    ports:
      - "8080:8080"
    restart: always
  frontend:
    build:
      context: ../frontend/
    ports:
      - "80:3000"
    restart: always
volumes:
  pg_data: {}