// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: api/router.proto

package api

import (
	context "context"
	models "github.com/DubrovEva/higher_search/backend/pkg/proto/models"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RouterClient is the client API for Router service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RouterClient interface {
	// user methods
	GetPersonalInfo(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*UserResponse, error)
	GetUser(ctx context.Context, in *models.UserID, opts ...grpc.CallOption) (*UserResponse, error)
	GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error)
	InsertUser(ctx context.Context, in *models.UserInfo, opts ...grpc.CallOption) (*UserResponse, error)
	UpdateUser(ctx context.Context, in *models.User, opts ...grpc.CallOption) (*SuccessResponse, error)
	// authorization methods
	AuthorizeUser(ctx context.Context, in *AuthorizationRequest, opts ...grpc.CallOption) (*UserIDResponse, error)
	IsAuth(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*models.AuthInfo, error)
	Logout(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*SuccessResponse, error)
	RegisterUser(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*UserIDResponse, error)
	// studorgs methods
	GetStudorg(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*StudorgResponse, error)
	CreateStudorg(ctx context.Context, in *models.StudorgInfo, opts ...grpc.CallOption) (*StudorgIDResponse, error)
	UpdateStudorg(ctx context.Context, in *models.Studorg, opts ...grpc.CallOption) (*SuccessResponse, error)
	GetAllStudorgs(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*StudorgsResponse, error)
	SearchStudorgs(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*StudorgsResponse, error)
	// user2studorg methods
	GetPersonalStudorgRole(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*RoleResponse, error)
	GetPersonalStudorgs(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*StudorgsResponse, error)
	GetPersonalStudorgsNumber(ctx context.Context, in *models.UserID, opts ...grpc.CallOption) (*NumberResponse, error)
	GetParticipants(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*ParticipantsResponse, error)
	GetOrganizers(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*ParticipantsResponse, error)
	GetParticipantsNumber(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*NumberResponse, error)
	AddToStudorg(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*SuccessResponse, error)
	DeleteFromStudorg(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*SuccessResponse, error)
	UpdateParticipant(ctx context.Context, in *models.Participant, opts ...grpc.CallOption) (*SuccessResponse, error)
	ModerateStudorg(ctx context.Context, in *models.Studorg, opts ...grpc.CallOption) (*SuccessResponse, error)
}

type routerClient struct {
	cc grpc.ClientConnInterface
}

func NewRouterClient(cc grpc.ClientConnInterface) RouterClient {
	return &routerClient{cc}
}

func (c *routerClient) GetPersonalInfo(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetPersonalInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetUser(ctx context.Context, in *models.UserID, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetUsers(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*UsersResponse, error) {
	out := new(UsersResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) InsertUser(ctx context.Context, in *models.UserInfo, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/router.Router/InsertUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) UpdateUser(ctx context.Context, in *models.User, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/router.Router/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) AuthorizeUser(ctx context.Context, in *AuthorizationRequest, opts ...grpc.CallOption) (*UserIDResponse, error) {
	out := new(UserIDResponse)
	err := c.cc.Invoke(ctx, "/router.Router/AuthorizeUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) IsAuth(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*models.AuthInfo, error) {
	out := new(models.AuthInfo)
	err := c.cc.Invoke(ctx, "/router.Router/IsAuth", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) Logout(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/router.Router/Logout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) RegisterUser(ctx context.Context, in *RegistrationRequest, opts ...grpc.CallOption) (*UserIDResponse, error) {
	out := new(UserIDResponse)
	err := c.cc.Invoke(ctx, "/router.Router/RegisterUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetStudorg(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*StudorgResponse, error) {
	out := new(StudorgResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetStudorg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) CreateStudorg(ctx context.Context, in *models.StudorgInfo, opts ...grpc.CallOption) (*StudorgIDResponse, error) {
	out := new(StudorgIDResponse)
	err := c.cc.Invoke(ctx, "/router.Router/CreateStudorg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) UpdateStudorg(ctx context.Context, in *models.Studorg, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/router.Router/UpdateStudorg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetAllStudorgs(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*StudorgsResponse, error) {
	out := new(StudorgsResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetAllStudorgs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) SearchStudorgs(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*StudorgsResponse, error) {
	out := new(StudorgsResponse)
	err := c.cc.Invoke(ctx, "/router.Router/SearchStudorgs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetPersonalStudorgRole(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*RoleResponse, error) {
	out := new(RoleResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetPersonalStudorgRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetPersonalStudorgs(ctx context.Context, in *WithoutParameters, opts ...grpc.CallOption) (*StudorgsResponse, error) {
	out := new(StudorgsResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetPersonalStudorgs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetPersonalStudorgsNumber(ctx context.Context, in *models.UserID, opts ...grpc.CallOption) (*NumberResponse, error) {
	out := new(NumberResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetPersonalStudorgsNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetParticipants(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*ParticipantsResponse, error) {
	out := new(ParticipantsResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetParticipants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetOrganizers(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*ParticipantsResponse, error) {
	out := new(ParticipantsResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetOrganizers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) GetParticipantsNumber(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*NumberResponse, error) {
	out := new(NumberResponse)
	err := c.cc.Invoke(ctx, "/router.Router/GetParticipantsNumber", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) AddToStudorg(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/router.Router/AddToStudorg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) DeleteFromStudorg(ctx context.Context, in *models.StudorgID, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/router.Router/DeleteFromStudorg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) UpdateParticipant(ctx context.Context, in *models.Participant, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/router.Router/UpdateParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *routerClient) ModerateStudorg(ctx context.Context, in *models.Studorg, opts ...grpc.CallOption) (*SuccessResponse, error) {
	out := new(SuccessResponse)
	err := c.cc.Invoke(ctx, "/router.Router/ModerateStudorg", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RouterServer is the server API for Router service.
// All implementations must embed UnimplementedRouterServer
// for forward compatibility
type RouterServer interface {
	// user methods
	GetPersonalInfo(context.Context, *WithoutParameters) (*UserResponse, error)
	GetUser(context.Context, *models.UserID) (*UserResponse, error)
	GetUsers(context.Context, *UsersRequest) (*UsersResponse, error)
	InsertUser(context.Context, *models.UserInfo) (*UserResponse, error)
	UpdateUser(context.Context, *models.User) (*SuccessResponse, error)
	// authorization methods
	AuthorizeUser(context.Context, *AuthorizationRequest) (*UserIDResponse, error)
	IsAuth(context.Context, *WithoutParameters) (*models.AuthInfo, error)
	Logout(context.Context, *WithoutParameters) (*SuccessResponse, error)
	RegisterUser(context.Context, *RegistrationRequest) (*UserIDResponse, error)
	// studorgs methods
	GetStudorg(context.Context, *models.StudorgID) (*StudorgResponse, error)
	CreateStudorg(context.Context, *models.StudorgInfo) (*StudorgIDResponse, error)
	UpdateStudorg(context.Context, *models.Studorg) (*SuccessResponse, error)
	GetAllStudorgs(context.Context, *WithoutParameters) (*StudorgsResponse, error)
	SearchStudorgs(context.Context, *SearchRequest) (*StudorgsResponse, error)
	// user2studorg methods
	GetPersonalStudorgRole(context.Context, *models.StudorgID) (*RoleResponse, error)
	GetPersonalStudorgs(context.Context, *WithoutParameters) (*StudorgsResponse, error)
	GetPersonalStudorgsNumber(context.Context, *models.UserID) (*NumberResponse, error)
	GetParticipants(context.Context, *models.StudorgID) (*ParticipantsResponse, error)
	GetOrganizers(context.Context, *models.StudorgID) (*ParticipantsResponse, error)
	GetParticipantsNumber(context.Context, *models.StudorgID) (*NumberResponse, error)
	AddToStudorg(context.Context, *models.StudorgID) (*SuccessResponse, error)
	DeleteFromStudorg(context.Context, *models.StudorgID) (*SuccessResponse, error)
	UpdateParticipant(context.Context, *models.Participant) (*SuccessResponse, error)
	ModerateStudorg(context.Context, *models.Studorg) (*SuccessResponse, error)
	mustEmbedUnimplementedRouterServer()
}

// UnimplementedRouterServer must be embedded to have forward compatible implementations.
type UnimplementedRouterServer struct {
}

func (UnimplementedRouterServer) GetPersonalInfo(context.Context, *WithoutParameters) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonalInfo not implemented")
}
func (UnimplementedRouterServer) GetUser(context.Context, *models.UserID) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (UnimplementedRouterServer) GetUsers(context.Context, *UsersRequest) (*UsersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUsers not implemented")
}
func (UnimplementedRouterServer) InsertUser(context.Context, *models.UserInfo) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertUser not implemented")
}
func (UnimplementedRouterServer) UpdateUser(context.Context, *models.User) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (UnimplementedRouterServer) AuthorizeUser(context.Context, *AuthorizationRequest) (*UserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthorizeUser not implemented")
}
func (UnimplementedRouterServer) IsAuth(context.Context, *WithoutParameters) (*models.AuthInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsAuth not implemented")
}
func (UnimplementedRouterServer) Logout(context.Context, *WithoutParameters) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Logout not implemented")
}
func (UnimplementedRouterServer) RegisterUser(context.Context, *RegistrationRequest) (*UserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterUser not implemented")
}
func (UnimplementedRouterServer) GetStudorg(context.Context, *models.StudorgID) (*StudorgResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudorg not implemented")
}
func (UnimplementedRouterServer) CreateStudorg(context.Context, *models.StudorgInfo) (*StudorgIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateStudorg not implemented")
}
func (UnimplementedRouterServer) UpdateStudorg(context.Context, *models.Studorg) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStudorg not implemented")
}
func (UnimplementedRouterServer) GetAllStudorgs(context.Context, *WithoutParameters) (*StudorgsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllStudorgs not implemented")
}
func (UnimplementedRouterServer) SearchStudorgs(context.Context, *SearchRequest) (*StudorgsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchStudorgs not implemented")
}
func (UnimplementedRouterServer) GetPersonalStudorgRole(context.Context, *models.StudorgID) (*RoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonalStudorgRole not implemented")
}
func (UnimplementedRouterServer) GetPersonalStudorgs(context.Context, *WithoutParameters) (*StudorgsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonalStudorgs not implemented")
}
func (UnimplementedRouterServer) GetPersonalStudorgsNumber(context.Context, *models.UserID) (*NumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPersonalStudorgsNumber not implemented")
}
func (UnimplementedRouterServer) GetParticipants(context.Context, *models.StudorgID) (*ParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipants not implemented")
}
func (UnimplementedRouterServer) GetOrganizers(context.Context, *models.StudorgID) (*ParticipantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOrganizers not implemented")
}
func (UnimplementedRouterServer) GetParticipantsNumber(context.Context, *models.StudorgID) (*NumberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetParticipantsNumber not implemented")
}
func (UnimplementedRouterServer) AddToStudorg(context.Context, *models.StudorgID) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToStudorg not implemented")
}
func (UnimplementedRouterServer) DeleteFromStudorg(context.Context, *models.StudorgID) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFromStudorg not implemented")
}
func (UnimplementedRouterServer) UpdateParticipant(context.Context, *models.Participant) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParticipant not implemented")
}
func (UnimplementedRouterServer) ModerateStudorg(context.Context, *models.Studorg) (*SuccessResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModerateStudorg not implemented")
}
func (UnimplementedRouterServer) mustEmbedUnimplementedRouterServer() {}

// UnsafeRouterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RouterServer will
// result in compilation errors.
type UnsafeRouterServer interface {
	mustEmbedUnimplementedRouterServer()
}

func RegisterRouterServer(s grpc.ServiceRegistrar, srv RouterServer) {
	s.RegisterService(&Router_ServiceDesc, srv)
}

func _Router_GetPersonalInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithoutParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetPersonalInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetPersonalInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetPersonalInfo(ctx, req.(*WithoutParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetUser(ctx, req.(*models.UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetUsers(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_InsertUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.UserInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).InsertUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/InsertUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).InsertUser(ctx, req.(*models.UserInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).UpdateUser(ctx, req.(*models.User))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_AuthorizeUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).AuthorizeUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/AuthorizeUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).AuthorizeUser(ctx, req.(*AuthorizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_IsAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithoutParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).IsAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/IsAuth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).IsAuth(ctx, req.(*WithoutParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_Logout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithoutParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).Logout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/Logout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).Logout(ctx, req.(*WithoutParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_RegisterUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).RegisterUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/RegisterUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).RegisterUser(ctx, req.(*RegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetStudorg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.StudorgID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetStudorg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetStudorg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetStudorg(ctx, req.(*models.StudorgID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_CreateStudorg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.StudorgInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).CreateStudorg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/CreateStudorg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).CreateStudorg(ctx, req.(*models.StudorgInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_UpdateStudorg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.Studorg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).UpdateStudorg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/UpdateStudorg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).UpdateStudorg(ctx, req.(*models.Studorg))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetAllStudorgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithoutParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetAllStudorgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetAllStudorgs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetAllStudorgs(ctx, req.(*WithoutParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_SearchStudorgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).SearchStudorgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/SearchStudorgs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).SearchStudorgs(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetPersonalStudorgRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.StudorgID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetPersonalStudorgRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetPersonalStudorgRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetPersonalStudorgRole(ctx, req.(*models.StudorgID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetPersonalStudorgs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithoutParameters)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetPersonalStudorgs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetPersonalStudorgs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetPersonalStudorgs(ctx, req.(*WithoutParameters))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetPersonalStudorgsNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.UserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetPersonalStudorgsNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetPersonalStudorgsNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetPersonalStudorgsNumber(ctx, req.(*models.UserID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.StudorgID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetParticipants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetParticipants(ctx, req.(*models.StudorgID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetOrganizers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.StudorgID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetOrganizers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetOrganizers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetOrganizers(ctx, req.(*models.StudorgID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_GetParticipantsNumber_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.StudorgID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).GetParticipantsNumber(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/GetParticipantsNumber",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).GetParticipantsNumber(ctx, req.(*models.StudorgID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_AddToStudorg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.StudorgID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).AddToStudorg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/AddToStudorg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).AddToStudorg(ctx, req.(*models.StudorgID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_DeleteFromStudorg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.StudorgID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).DeleteFromStudorg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/DeleteFromStudorg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).DeleteFromStudorg(ctx, req.(*models.StudorgID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_UpdateParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.Participant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).UpdateParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/UpdateParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).UpdateParticipant(ctx, req.(*models.Participant))
	}
	return interceptor(ctx, in, info, handler)
}

func _Router_ModerateStudorg_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(models.Studorg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RouterServer).ModerateStudorg(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/router.Router/ModerateStudorg",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RouterServer).ModerateStudorg(ctx, req.(*models.Studorg))
	}
	return interceptor(ctx, in, info, handler)
}

// Router_ServiceDesc is the grpc.ServiceDesc for Router service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Router_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "router.Router",
	HandlerType: (*RouterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPersonalInfo",
			Handler:    _Router_GetPersonalInfo_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _Router_GetUser_Handler,
		},
		{
			MethodName: "GetUsers",
			Handler:    _Router_GetUsers_Handler,
		},
		{
			MethodName: "InsertUser",
			Handler:    _Router_InsertUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _Router_UpdateUser_Handler,
		},
		{
			MethodName: "AuthorizeUser",
			Handler:    _Router_AuthorizeUser_Handler,
		},
		{
			MethodName: "IsAuth",
			Handler:    _Router_IsAuth_Handler,
		},
		{
			MethodName: "Logout",
			Handler:    _Router_Logout_Handler,
		},
		{
			MethodName: "RegisterUser",
			Handler:    _Router_RegisterUser_Handler,
		},
		{
			MethodName: "GetStudorg",
			Handler:    _Router_GetStudorg_Handler,
		},
		{
			MethodName: "CreateStudorg",
			Handler:    _Router_CreateStudorg_Handler,
		},
		{
			MethodName: "UpdateStudorg",
			Handler:    _Router_UpdateStudorg_Handler,
		},
		{
			MethodName: "GetAllStudorgs",
			Handler:    _Router_GetAllStudorgs_Handler,
		},
		{
			MethodName: "SearchStudorgs",
			Handler:    _Router_SearchStudorgs_Handler,
		},
		{
			MethodName: "GetPersonalStudorgRole",
			Handler:    _Router_GetPersonalStudorgRole_Handler,
		},
		{
			MethodName: "GetPersonalStudorgs",
			Handler:    _Router_GetPersonalStudorgs_Handler,
		},
		{
			MethodName: "GetPersonalStudorgsNumber",
			Handler:    _Router_GetPersonalStudorgsNumber_Handler,
		},
		{
			MethodName: "GetParticipants",
			Handler:    _Router_GetParticipants_Handler,
		},
		{
			MethodName: "GetOrganizers",
			Handler:    _Router_GetOrganizers_Handler,
		},
		{
			MethodName: "GetParticipantsNumber",
			Handler:    _Router_GetParticipantsNumber_Handler,
		},
		{
			MethodName: "AddToStudorg",
			Handler:    _Router_AddToStudorg_Handler,
		},
		{
			MethodName: "DeleteFromStudorg",
			Handler:    _Router_DeleteFromStudorg_Handler,
		},
		{
			MethodName: "UpdateParticipant",
			Handler:    _Router_UpdateParticipant_Handler,
		},
		{
			MethodName: "ModerateStudorg",
			Handler:    _Router_ModerateStudorg_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/router.proto",
}
