// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.21.12
// source: api/router.proto

package api

import (
	models "github.com/DubrovEva/higher_search/backend/pkg/proto/models"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WithoutParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WithoutParameters) Reset() {
	*x = WithoutParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithoutParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithoutParameters) ProtoMessage() {}

func (x *WithoutParameters) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithoutParameters.ProtoReflect.Descriptor instead.
func (*WithoutParameters) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{0}
}

type UserResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*UserResponse_Err
	//	*UserResponse_User
	Response isUserResponse_Response `protobuf_oneof:"response"`
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{1}
}

func (m *UserResponse) GetResponse() isUserResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *UserResponse) GetErr() *Error {
	if x, ok := x.GetResponse().(*UserResponse_Err); ok {
		return x.Err
	}
	return nil
}

func (x *UserResponse) GetUser() *models.User {
	if x, ok := x.GetResponse().(*UserResponse_User); ok {
		return x.User
	}
	return nil
}

type isUserResponse_Response interface {
	isUserResponse_Response()
}

type UserResponse_Err struct {
	Err *Error `protobuf:"bytes,1,opt,name=err,proto3,oneof"`
}

type UserResponse_User struct {
	User *models.User `protobuf:"bytes,2,opt,name=user,proto3,oneof"`
}

func (*UserResponse_Err) isUserResponse_Response() {}

func (*UserResponse_User) isUserResponse_Response() {}

type UsersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*UsersResponse_Err
	//	*UsersResponse_Users
	Response isUsersResponse_Response `protobuf_oneof:"response"`
}

func (x *UsersResponse) Reset() {
	*x = UsersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersResponse) ProtoMessage() {}

func (x *UsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersResponse.ProtoReflect.Descriptor instead.
func (*UsersResponse) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{2}
}

func (m *UsersResponse) GetResponse() isUsersResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *UsersResponse) GetErr() *Error {
	if x, ok := x.GetResponse().(*UsersResponse_Err); ok {
		return x.Err
	}
	return nil
}

func (x *UsersResponse) GetUsers() *models.Users {
	if x, ok := x.GetResponse().(*UsersResponse_Users); ok {
		return x.Users
	}
	return nil
}

type isUsersResponse_Response interface {
	isUsersResponse_Response()
}

type UsersResponse_Err struct {
	Err *Error `protobuf:"bytes,1,opt,name=err,proto3,oneof"`
}

type UsersResponse_Users struct {
	Users *models.Users `protobuf:"bytes,2,opt,name=users,proto3,oneof"`
}

func (*UsersResponse_Err) isUsersResponse_Response() {}

func (*UsersResponse_Users) isUsersResponse_Response() {}

type StudorgResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*StudorgResponse_Err
	//	*StudorgResponse_Studorg
	Response isStudorgResponse_Response `protobuf_oneof:"response"`
}

func (x *StudorgResponse) Reset() {
	*x = StudorgResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudorgResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudorgResponse) ProtoMessage() {}

func (x *StudorgResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudorgResponse.ProtoReflect.Descriptor instead.
func (*StudorgResponse) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{3}
}

func (m *StudorgResponse) GetResponse() isStudorgResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *StudorgResponse) GetErr() *Error {
	if x, ok := x.GetResponse().(*StudorgResponse_Err); ok {
		return x.Err
	}
	return nil
}

func (x *StudorgResponse) GetStudorg() *models.Studorg {
	if x, ok := x.GetResponse().(*StudorgResponse_Studorg); ok {
		return x.Studorg
	}
	return nil
}

type isStudorgResponse_Response interface {
	isStudorgResponse_Response()
}

type StudorgResponse_Err struct {
	Err *Error `protobuf:"bytes,1,opt,name=err,proto3,oneof"`
}

type StudorgResponse_Studorg struct {
	Studorg *models.Studorg `protobuf:"bytes,2,opt,name=studorg,proto3,oneof"`
}

func (*StudorgResponse_Err) isStudorgResponse_Response() {}

func (*StudorgResponse_Studorg) isStudorgResponse_Response() {}

type StudorgsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*StudorgsResponse_Err
	//	*StudorgsResponse_Studorgs
	Response isStudorgsResponse_Response `protobuf_oneof:"response"`
}

func (x *StudorgsResponse) Reset() {
	*x = StudorgsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StudorgsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudorgsResponse) ProtoMessage() {}

func (x *StudorgsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudorgsResponse.ProtoReflect.Descriptor instead.
func (*StudorgsResponse) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{4}
}

func (m *StudorgsResponse) GetResponse() isStudorgsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *StudorgsResponse) GetErr() *Error {
	if x, ok := x.GetResponse().(*StudorgsResponse_Err); ok {
		return x.Err
	}
	return nil
}

func (x *StudorgsResponse) GetStudorgs() *models.Studorgs {
	if x, ok := x.GetResponse().(*StudorgsResponse_Studorgs); ok {
		return x.Studorgs
	}
	return nil
}

type isStudorgsResponse_Response interface {
	isStudorgsResponse_Response()
}

type StudorgsResponse_Err struct {
	Err *Error `protobuf:"bytes,1,opt,name=err,proto3,oneof"`
}

type StudorgsResponse_Studorgs struct {
	Studorgs *models.Studorgs `protobuf:"bytes,2,opt,name=studorgs,proto3,oneof"`
}

func (*StudorgsResponse_Err) isStudorgsResponse_Response() {}

func (*StudorgsResponse_Studorgs) isStudorgsResponse_Response() {}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{5}
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UsersNumberResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*UsersNumberResponse_Err
	//	*UsersNumberResponse_Number
	Response isUsersNumberResponse_Response `protobuf_oneof:"response"`
}

func (x *UsersNumberResponse) Reset() {
	*x = UsersNumberResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsersNumberResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersNumberResponse) ProtoMessage() {}

func (x *UsersNumberResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersNumberResponse.ProtoReflect.Descriptor instead.
func (*UsersNumberResponse) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{6}
}

func (m *UsersNumberResponse) GetResponse() isUsersNumberResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *UsersNumberResponse) GetErr() *Error {
	if x, ok := x.GetResponse().(*UsersNumberResponse_Err); ok {
		return x.Err
	}
	return nil
}

func (x *UsersNumberResponse) GetNumber() int64 {
	if x, ok := x.GetResponse().(*UsersNumberResponse_Number); ok {
		return x.Number
	}
	return 0
}

type isUsersNumberResponse_Response interface {
	isUsersNumberResponse_Response()
}

type UsersNumberResponse_Err struct {
	Err *Error `protobuf:"bytes,1,opt,name=err,proto3,oneof"`
}

type UsersNumberResponse_Number struct {
	Number int64 `protobuf:"varint,2,opt,name=number,proto3,oneof"`
}

func (*UsersNumberResponse_Err) isUsersNumberResponse_Response() {}

func (*UsersNumberResponse_Number) isUsersNumberResponse_Response() {}

type AuthorizationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *AuthorizationRequest) Reset() {
	*x = AuthorizationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationRequest) ProtoMessage() {}

func (x *AuthorizationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationRequest.ProtoReflect.Descriptor instead.
func (*AuthorizationRequest) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{7}
}

func (x *AuthorizationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthorizationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ValidationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*ValidationResponse_Err
	//	*ValidationResponse_Valid
	Response isValidationResponse_Response `protobuf_oneof:"response"`
}

func (x *ValidationResponse) Reset() {
	*x = ValidationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResponse) ProtoMessage() {}

func (x *ValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResponse.ProtoReflect.Descriptor instead.
func (*ValidationResponse) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{8}
}

func (m *ValidationResponse) GetResponse() isValidationResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ValidationResponse) GetErr() *Error {
	if x, ok := x.GetResponse().(*ValidationResponse_Err); ok {
		return x.Err
	}
	return nil
}

func (x *ValidationResponse) GetValid() bool {
	if x, ok := x.GetResponse().(*ValidationResponse_Valid); ok {
		return x.Valid
	}
	return false
}

type isValidationResponse_Response interface {
	isValidationResponse_Response()
}

type ValidationResponse_Err struct {
	Err *Error `protobuf:"bytes,1,opt,name=err,proto3,oneof"`
}

type ValidationResponse_Valid struct {
	Valid bool `protobuf:"varint,2,opt,name=valid,proto3,oneof"`
}

func (*ValidationResponse_Err) isValidationResponse_Response() {}

func (*ValidationResponse_Valid) isValidationResponse_Response() {}

type RegistrationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email    string `protobuf:"bytes,1,opt,name=Email,proto3" json:"Email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Surname  string `protobuf:"bytes,4,opt,name=Surname,proto3" json:"Surname,omitempty"`
}

func (x *RegistrationRequest) Reset() {
	*x = RegistrationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_router_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationRequest) ProtoMessage() {}

func (x *RegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_router_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationRequest.ProtoReflect.Descriptor instead.
func (*RegistrationRequest) Descriptor() ([]byte, []int) {
	return file_api_router_proto_rawDescGZIP(), []int{9}
}

func (x *RegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *RegistrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegistrationRequest) GetSurname() string {
	if x != nil {
		return x.Surname
	}
	return ""
}

var File_api_router_proto protoreflect.FileDescriptor

var file_api_router_proto_rawDesc = []byte{
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x06, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x1a, 0x11, 0x6d, 0x6f, 0x64, 0x65,
	0x6c, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x14, 0x6d,
	0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x22, 0x5f, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x20, 0x0a, 0x04, 0x75,
	0x73, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x48, 0x00, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x42, 0x0a, 0x0a,
	0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x63, 0x0a, 0x0d, 0x55, 0x73, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x72,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x23, 0x0a,
	0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x48, 0x00, 0x52, 0x05, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x6e,
	0x0a, 0x0f, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d,
	0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52,
	0x03, 0x65, 0x72, 0x72, 0x12, 0x2c, 0x0a, 0x07, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x2e,
	0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x48, 0x00, 0x52, 0x07, 0x73, 0x74, 0x75, 0x64, 0x6f,
	0x72, 0x67, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x72,
	0x0a, 0x10, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00,
	0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x2f, 0x0a, 0x08, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72,
	0x67, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x73, 0x48, 0x00, 0x52, 0x08, 0x73, 0x74,
	0x75, 0x64, 0x6f, 0x72, 0x67, 0x73, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x19, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x5e, 0x0a,
	0x13, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72, 0x12, 0x18, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x00, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x48, 0x0a,
	0x14, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70,
	0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x5b, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x69, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a,
	0x03, 0x65, 0x72, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x03, 0x65, 0x72, 0x72,
	0x12, 0x16, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x48,
	0x00, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x75, 0x0a, 0x13, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45,
	0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x53, 0x75, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xa5, 0x06, 0x0a, 0x06,
	0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x12, 0x2d, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x1a,
	0x14, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x73, 0x12, 0x0d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x73,
	0x1a, 0x15, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x65, 0x72,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x14, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x0a, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x0a, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x14, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x43, 0x0a, 0x0d, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x72, 0x6f, 0x75,
	0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x41, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1b, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x4e, 0x0a, 0x15, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x2e, 0x72,
	0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x1a, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72,
	0x2e, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74,
	0x75, 0x64, 0x6f, 0x72, 0x67, 0x73, 0x12, 0x0c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x1a, 0x15, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x73, 0x12, 0x45, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x73, 0x12, 0x19, 0x2e,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x18, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65,
	0x72, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67,
	0x12, 0x12, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x6f,
	0x72, 0x67, 0x49, 0x44, 0x1a, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x6f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a,
	0x0d, 0x49, 0x6e, 0x73, 0x65, 0x72, 0x74, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x12, 0x14,
	0x2e, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67,
	0x49, 0x6e, 0x66, 0x6f, 0x1a, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74,
	0x75, 0x64, 0x6f, 0x72, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a,
	0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x12, 0x10,
	0x2e, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67,
	0x1a, 0x17, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x75, 0x64, 0x6f, 0x72,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x48, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x53, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x55, 0x73, 0x65, 0x72, 0x73, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x12, 0x2e, 0x73, 0x74, 0x75, 0x64, 0x6f, 0x72, 0x67, 0x2e, 0x53, 0x74, 0x75,
	0x64, 0x6f, 0x72, 0x67, 0x49, 0x44, 0x1a, 0x1b, 0x2e, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x73, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x44, 0x75, 0x62, 0x72, 0x6f, 0x76, 0x45, 0x76, 0x61, 0x2f, 0x62, 0x61, 0x63, 0x6b,
	0x65, 0x6e, 0x64, 0x2f, 0x68, 0x69, 0x67, 0x68, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x61, 0x72, 0x63,
	0x68, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_router_proto_rawDescOnce sync.Once
	file_api_router_proto_rawDescData = file_api_router_proto_rawDesc
)

func file_api_router_proto_rawDescGZIP() []byte {
	file_api_router_proto_rawDescOnce.Do(func() {
		file_api_router_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_router_proto_rawDescData)
	})
	return file_api_router_proto_rawDescData
}

var file_api_router_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_router_proto_goTypes = []interface{}{
	(*WithoutParameters)(nil),    // 0: router.WithoutParameters
	(*UserResponse)(nil),         // 1: router.UserResponse
	(*UsersResponse)(nil),        // 2: router.UsersResponse
	(*StudorgResponse)(nil),      // 3: router.StudorgResponse
	(*StudorgsResponse)(nil),     // 4: router.StudorgsResponse
	(*Error)(nil),                // 5: router.Error
	(*UsersNumberResponse)(nil),  // 6: router.UsersNumberResponse
	(*AuthorizationRequest)(nil), // 7: router.AuthorizationRequest
	(*ValidationResponse)(nil),   // 8: router.ValidationResponse
	(*RegistrationRequest)(nil),  // 9: router.RegistrationRequest
	(*models.User)(nil),          // 10: user.User
	(*models.Users)(nil),         // 11: user.Users
	(*models.Studorg)(nil),       // 12: studorg.Studorg
	(*models.Studorgs)(nil),      // 13: studorg.Studorgs
	(*models.UserID)(nil),        // 14: user.UserID
	(*models.UserIDs)(nil),       // 15: user.UserIDs
	(*models.UserInfo)(nil),      // 16: user.UserInfo
	(*models.StudorgID)(nil),     // 17: studorg.StudorgID
	(*models.StudorgInfo)(nil),   // 18: studorg.StudorgInfo
	(*models.UserStudorgs)(nil),  // 19: studorg.UserStudorgs
}
var file_api_router_proto_depIdxs = []int32{
	5,  // 0: router.UserResponse.err:type_name -> router.Error
	10, // 1: router.UserResponse.user:type_name -> user.User
	5,  // 2: router.UsersResponse.err:type_name -> router.Error
	11, // 3: router.UsersResponse.users:type_name -> user.Users
	5,  // 4: router.StudorgResponse.err:type_name -> router.Error
	12, // 5: router.StudorgResponse.studorg:type_name -> studorg.Studorg
	5,  // 6: router.StudorgsResponse.err:type_name -> router.Error
	13, // 7: router.StudorgsResponse.studorgs:type_name -> studorg.Studorgs
	5,  // 8: router.UsersNumberResponse.err:type_name -> router.Error
	5,  // 9: router.ValidationResponse.err:type_name -> router.Error
	14, // 10: router.Router.GetUser:input_type -> user.UserID
	15, // 11: router.Router.GetUsers:input_type -> user.UserIDs
	16, // 12: router.Router.InsertUser:input_type -> user.UserInfo
	10, // 13: router.Router.UpdateUser:input_type -> user.User
	7,  // 14: router.Router.AuthorizeUser:input_type -> router.AuthorizationRequest
	9,  // 15: router.Router.RegisterUser:input_type -> router.RegistrationRequest
	0,  // 16: router.Router.ValidateAuthorization:input_type -> router.WithoutParameters
	14, // 17: router.Router.GetUserStudorgs:input_type -> user.UserID
	0,  // 18: router.Router.GetAllStudorgs:input_type -> router.WithoutParameters
	17, // 19: router.Router.GetStudorg:input_type -> studorg.StudorgID
	18, // 20: router.Router.InsertStudorg:input_type -> studorg.StudorgInfo
	12, // 21: router.Router.UpdateStudorg:input_type -> studorg.Studorg
	17, // 22: router.Router.GetStudorgUsersNumber:input_type -> studorg.StudorgID
	1,  // 23: router.Router.GetUser:output_type -> router.UserResponse
	2,  // 24: router.Router.GetUsers:output_type -> router.UsersResponse
	1,  // 25: router.Router.InsertUser:output_type -> router.UserResponse
	1,  // 26: router.Router.UpdateUser:output_type -> router.UserResponse
	1,  // 27: router.Router.AuthorizeUser:output_type -> router.UserResponse
	1,  // 28: router.Router.RegisterUser:output_type -> router.UserResponse
	8,  // 29: router.Router.ValidateAuthorization:output_type -> router.ValidationResponse
	19, // 30: router.Router.GetUserStudorgs:output_type -> studorg.UserStudorgs
	4,  // 31: router.Router.GetAllStudorgs:output_type -> router.StudorgsResponse
	3,  // 32: router.Router.GetStudorg:output_type -> router.StudorgResponse
	3,  // 33: router.Router.InsertStudorg:output_type -> router.StudorgResponse
	3,  // 34: router.Router.UpdateStudorg:output_type -> router.StudorgResponse
	6,  // 35: router.Router.GetStudorgUsersNumber:output_type -> router.UsersNumberResponse
	23, // [23:36] is the sub-list for method output_type
	10, // [10:23] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_router_proto_init() }
func file_api_router_proto_init() {
	if File_api_router_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_router_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithoutParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudorgResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StudorgsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsersNumberResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValidationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_router_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegistrationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_router_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*UserResponse_Err)(nil),
		(*UserResponse_User)(nil),
	}
	file_api_router_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*UsersResponse_Err)(nil),
		(*UsersResponse_Users)(nil),
	}
	file_api_router_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*StudorgResponse_Err)(nil),
		(*StudorgResponse_Studorg)(nil),
	}
	file_api_router_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*StudorgsResponse_Err)(nil),
		(*StudorgsResponse_Studorgs)(nil),
	}
	file_api_router_proto_msgTypes[6].OneofWrappers = []interface{}{
		(*UsersNumberResponse_Err)(nil),
		(*UsersNumberResponse_Number)(nil),
	}
	file_api_router_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ValidationResponse_Err)(nil),
		(*ValidationResponse_Valid)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_router_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_router_proto_goTypes,
		DependencyIndexes: file_api_router_proto_depIdxs,
		MessageInfos:      file_api_router_proto_msgTypes,
	}.Build()
	File_api_router_proto = out.File
	file_api_router_proto_rawDesc = nil
	file_api_router_proto_goTypes = nil
	file_api_router_proto_depIdxs = nil
}
