// @generated by protobuf-ts 2.9.4 with parameter long_type_string
// @generated from protobuf file "models/errors.proto" (package "errors", syntax proto3)
// tslint:disable
/**
 * @generated from protobuf enum errors.ErrorCode
 */
export enum ErrorCode {
    /**
     * @generated from protobuf enum value: UNKNOWN_ERROR = 0;
     */
    UNKNOWN_ERROR = 0,
    /**
     * @generated from protobuf enum value: AUTH_FAILED = 1;
     */
    AUTH_FAILED = 1
}
