// @generated by protobuf-ts 2.9.4 with parameter long_type_string
// @generated from protobuf file "models/user2studorg.proto" (package "user2studorg", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../google/protobuf/timestamp";
import { StudorgRole } from "./studorg";
import { StudorgID } from "./studorg";
import { UserID } from "./user";
/**
 * @generated from protobuf message user2studorg.User2Studorg
 */
export interface User2Studorg {
    /**
     * @generated from protobuf field: user.UserID userID = 1;
     */
    userID?: UserID;
    /**
     * @generated from protobuf field: studorg.StudorgID studorgID = 2;
     */
    studorgID?: StudorgID;
    /**
     * @generated from protobuf field: studorg.StudorgRole role = 3;
     */
    role: StudorgRole;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp admissionTime = 4;
     */
    admissionTime?: Timestamp;
    /**
     * @generated from protobuf field: string contactInfo = 5;
     */
    contactInfo: string;
    /**
     * @generated from protobuf field: string customRole = 6;
     */
    customRole: string;
    /**
     * @generated from protobuf field: string info = 7;
     */
    info: string;
    /**
     * @generated from protobuf field: bool isContact = 8;
     */
    isContact: boolean;
}
// @generated message type with reflection information, may provide speed optimized methods
class User2Studorg$Type extends MessageType<User2Studorg> {
    constructor() {
        super("user2studorg.User2Studorg", [
            { no: 1, name: "userID", kind: "message", T: () => UserID },
            { no: 2, name: "studorgID", kind: "message", T: () => StudorgID },
            { no: 3, name: "role", kind: "enum", T: () => ["studorg.StudorgRole", StudorgRole] },
            { no: 4, name: "admissionTime", kind: "message", T: () => Timestamp },
            { no: 5, name: "contactInfo", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "customRole", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "info", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "isContact", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<User2Studorg>): User2Studorg {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.role = 0;
        message.contactInfo = "";
        message.customRole = "";
        message.info = "";
        message.isContact = false;
        if (value !== undefined)
            reflectionMergePartial<User2Studorg>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User2Studorg): User2Studorg {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* user.UserID userID */ 1:
                    message.userID = UserID.internalBinaryRead(reader, reader.uint32(), options, message.userID);
                    break;
                case /* studorg.StudorgID studorgID */ 2:
                    message.studorgID = StudorgID.internalBinaryRead(reader, reader.uint32(), options, message.studorgID);
                    break;
                case /* studorg.StudorgRole role */ 3:
                    message.role = reader.int32();
                    break;
                case /* google.protobuf.Timestamp admissionTime */ 4:
                    message.admissionTime = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.admissionTime);
                    break;
                case /* string contactInfo */ 5:
                    message.contactInfo = reader.string();
                    break;
                case /* string customRole */ 6:
                    message.customRole = reader.string();
                    break;
                case /* string info */ 7:
                    message.info = reader.string();
                    break;
                case /* bool isContact */ 8:
                    message.isContact = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User2Studorg, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* user.UserID userID = 1; */
        if (message.userID)
            UserID.internalBinaryWrite(message.userID, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* studorg.StudorgID studorgID = 2; */
        if (message.studorgID)
            StudorgID.internalBinaryWrite(message.studorgID, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* studorg.StudorgRole role = 3; */
        if (message.role !== 0)
            writer.tag(3, WireType.Varint).int32(message.role);
        /* google.protobuf.Timestamp admissionTime = 4; */
        if (message.admissionTime)
            Timestamp.internalBinaryWrite(message.admissionTime, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string contactInfo = 5; */
        if (message.contactInfo !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.contactInfo);
        /* string customRole = 6; */
        if (message.customRole !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.customRole);
        /* string info = 7; */
        if (message.info !== "")
            writer.tag(7, WireType.LengthDelimited).string(message.info);
        /* bool isContact = 8; */
        if (message.isContact !== false)
            writer.tag(8, WireType.Varint).bool(message.isContact);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message user2studorg.User2Studorg
 */
export const User2Studorg = new User2Studorg$Type();
